class ResponseErrors:
    DEFAULT = 'An unexpected error occurred while processing this request'
    INVALID_JSON = 'Unable to parse JSON from the request body'
    INVALID_LOGIN = 'The username/password you specified is invalid'
    USER_DNE = 'User does not exist'
    ACCOUNT_DNE = 'Account does not exist'
    ACCOUNT_NO_ACCESS = 'Invalid account'
    ACCOUNT_EXISTS = 'Account already exists for this user'
    ACCOUNT_INVALID_ACTION = 'Invalid action for account'
    ACCOUNT_INSUFFICIENTFUNDS = 'Insufficient funds'
    STOCK_DNE = 'Stock does not exist'
    STOCK_EXISTS = 'Stock already exists'
    STOCK_DATA_UNAVAILABLE = 'Stock data is currently unavailable'
    NOT_ENOUGH_FUNDS = 'Not enough funds to make this trade'
    TOO_MANY_SHARES = 'Shares passed is greater than what is owned'