version: '3'
volumes:
  pg-data:
services:
  web:
    build: .
    command: "flask run"
    ports: 
      - "5000:5000"
    volumes:
      - .:/trader
    depends_on:
      - postgres
    environment:
      FLASK_ENV: development
  postgres:
    restart: always
    image: "postgres:latest"
    env_file:
      - ./instance/db.env
    volumes:
      - pg-data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"