"""primary key for stocks

Revision ID: 3e17257ffadd
Revises: 2e59716e1ee4
Create Date: 2020-10-03 21:52:26.645895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e17257ffadd'
down_revision = '2e59716e1ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('stocks_akey', 'stocks', ['account_id', 'symbol'])
    op.drop_constraint('stocks_symbol_key', 'stocks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('stocks_symbol_key', 'stocks', ['symbol'])
    op.drop_constraint('stocks_akey', 'stocks', type_='unique')
    # ### end Alembic commands ###
