"""update cascade setting

Revision ID: f36a535bc8d0
Revises: 513e7a73a9fb
Create Date: 2020-02-05 02:33:34.313462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36a535bc8d0'
down_revision = '513e7a73a9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stocks_account_id_fkey', 'stocks', type_='foreignkey')
    op.create_foreign_key(None, 'stocks', 'accounts', ['account_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.create_foreign_key('stocks_account_id_fkey', 'stocks', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
